### ISSUE TITLE
When starting, the edge table displays as if there is a filter

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-2018#180]
This is using the export branch, but may be in earlier builds

To reproduce: 

1. Open net.create
2. Click on edges tab
3. Note that several rows are transaprent
4. Click on filter tab
5. Clear filters (even though none are displayed as on)
6. Go to edges tab and table displays correctly

**Comment by benloh** [comment]
This should be fixed with 6868516b1b1046110bc85eec2751a207da16fcbb

The problem was that edge.source and edge.target is initially stored as a simple numeric id reference.  Only after D3 processes the data do the edge.source and edge.target objects become nodes.  So the filter logic mistakenly thought the edge's source/targets had been filtered out, so it unhighlighted the edge.  This is an annoying bit of how D3 does things that has bitten us multiple times in the past.

**Comment by jdanish** [comment]
That's annoying! Looks fixed, though! Thanks!

**Comment by benloh** [comment]
Fixed with #179
