### ISSUE TITLE
Socket error on DO in current dev build and beyond

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-2018#266]

**Comment by jdanish** [comment]
Note just the web socket error attached. This appears upon load on the DO run. The other errors are reported in #265 

These socket errors do not appear on a local run.

I can of course open the socket if it is a permission issue but wanted to check if this is a needed reload and not tied to something else?


![Image](https://github.com/netcreateorg/netcreate-2018/assets/5529898/c0e12d7b-9479-4700-b66e-9910a16d26d0)

**Comment by benloh** [comment]
Just making sure...did you pull the code, stop the server (`ctrl-c`), then rerun it?  I don't think I changed anything that should apply to ports.  The socket error appears related to the developer auto-reload code, which is called when the code changes.

On DO, you probably want to be using `npm run classroom` instead of `npm run dev` (which is what is called by the `./nc.js` shell command.  See https://github.com/netcreateorg/nc-multiplex (I could've sworn we had some documentation in the `netcreate-2018` wiki but I can't find it.

**Comment by jdanish** [comment]
I did grab new code but I’m using nc-multiplex so am not sure what it uses? I can try again with classroom when I land in an hour or 2

**Comment by jdanish** [comment]
OK, npm run classroom throws an error. 

<img width="933" alt="Screenshot 2023-05-30 at 3 03 10 PM" src="https://github.com/netcreateorg/netcreate-2018/assets/5529898/1f5b23ab-5e59-46e3-816f-0e8abffb1bcf">

However, if I do nom run package it seems to be OK?  So I am good for now, but ... odd?

**Comment by benloh** [comment]
I'm assuming this is the error on DO?  I can run it fine on my local machine.

**Comment by jdanish** [comment]
Correct, DO only. Since it goes away when I use npm run package instead of npm run classroom, I'm going to close this and assume it's a non issue and all of this may change later anyhow.
